export const AUTH_LOGIN_USER = 'LOGIN_USER';
export const AUTH_LOGOUT_USER = 'LOGOUT_USER';
export const AUTH_REGISTER_USER = 'REGISTER_USER';
export const AUTH_REFRESH_TOKEN = 'REFRESHED_TOKEN';

export const ALERT_SET = 'ALERT_SET';
export const ALERT_SET_MULTI = 'ALERT_SET_MULTI';
export const ALERT_CLEAR = 'ALERT_CLEAR';

export const APP_STATUS_PROCESSING = 'APP_STATUS_PROCESSING';
export const APP_STATUS_IDLE = 'APP_STATUS_IDLE';