// Main application types
export const MASTER_LOGIN_USER = 'MASTER_LOGIN_USER';
export const MASTER_LOGOUT_USER = 'MASTER_LOGOUT_USER';
export const MASTER_REGISTER_USER = 'MASTER_REGISTER_USER';
export const MASTER_SET_ALERT = 'MASTER_SET_ALERT';
export const MASTER_SET_MULTI_ALERT = 'MASTER_SET_MULTI_ALERT';
export const MASTER_CLEAR_ALERT = 'MASTER_CLEAR_ALERT';
export const MASTER_REFRESHED_TOKEN = 'MASTER_REFRESHED_TOKEN';
export const MASTER_APP_STATUS_PROCESSING = 'MASTER_APP_STATUS_PROCESSING';
export const MASTER_APP_STATUS_IDLE = 'MASTER_APP_STATUS_IDLE';